apiVersion: v1
kind: Service
metadata:
  name: admin-svc
  namespace: {{ .Values.namespace }}

spec:
  type: NodePort

  selector:
    app: {{ .Values.services.admin.name }}

  ports:
    - name: http
      port: {{ .Values.services.admin.port }}
      targetPort: {{ .Values.services.admin.port }}