apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: {{ .Values.namespace }}

spec:
  type: NodePort

  selector:
    app: {{ .Values.services.auth.name }}

  ports:
    - name: http
      port: {{ .Values.services.auth.port }}
      targetPort: {{ .Values.services.auth.port }}